export const SEARCH_MOVIE = "SEARCH_MOVIE";
export const ADD_FAVORITES_LIST = "ADD_FAVORITES_LIST";
export const REMOVE_MOVIE_FROM_FAVORITE_LIST = "REMOVE_MOVIE_FROM_FAVORITE_LIST"
export const REGISTER_FAVORITES = "REGISTER_FAVORITES"
export const GET_LIST_INTO_STATE = "GET_LIST_INTO_STATE"
export const GET_MOVIE_INFO_INTO_STATE = "GET_MOVIE_INFO_INTO_STATE"
